export const  businessCategories = [
  { id: 1, value: "accounting_finance", label: "Accounting/Finance" },
  { id: 2, value: "advertising_marketing", label: "Advertising/Marketing" },
  { id: 3, value: "agriculture", label: "Agriculture" },
  { id: 4, value: "arts_entertainment", label: "Arts/Entertainment" },
  { id: 5, value: "automotive", label: "Automotive" },
  { id: 6, value: "beauty_cosmetics", label: "Beauty/Cosmetics" },
  { id: 7, value: "construction_real_estate", label: "Construction/Real Estate" },
  { id: 8, value: "education_training", label: "Education/Training" },
  { id: 9, value: "electronics", label: "Electronics" },
  { id: 10, value: "energy_utilities", label: "Energy/Utilities" },
  { id: 11, value: "fashion_apparel", label: "Fashion/Apparel" },
  { id: 12, value: "food_beverage", label: "Food/Beverage" },
  { id: 13, value: "health_medical", label: "Health/Medical" },
  { id: 14, value: "hospitality_travel", label: "Hospitality/Travel" },
  { id: 15, value: "information_technology", label: "Information Technology (IT)" },
  { id: 16, value: "legal", label: "Legal" },
  { id: 17, value: "manufacturing", label: "Manufacturing" },
  { id: 18, value: "non_profit_charity", label: "Non-Profit/Charity" },
  { id: 19, value: "retail", label: "Retail" },
  { id: 20, value: "sports_recreation", label: "Sports/Recreation" },
  { id: 21, value: "telecommunications", label: "Telecommunications" },
  { id: 22, value: "transportation_logistics", label: "Transportation/Logistics" },
  { id: 23, value: "e_commerce", label: "E-commerce" },
  { id: 24, value: "consulting", label: "Consulting" },
  { id: 25, value: "environmental_services", label: "Environmental Services" },
];


export const nigerianStates = [
  { id: 1, value: "Abia", label: "Abia" },
  { id: 2, value: "Adamawa", label: "Adamawa" },
  { id: 3, value: "Akwa Ibom", label: "Akwa Ibom" },
  { id: 4, value: "Anambra", label: "Anambra" },
  { id: 5, value: "Bauchi", label: "Bauchi" },
  { id: 6, value: "Bayelsa", label: "Bayelsa" },
  { id: 7, value: "Benue", label: "Benue" },
  { id: 8, value: "Borno", label: "Borno" },
  { id: 9, value: "Cross River", label: "Cross River" },
  { id: 10, value: "Delta", label: "Delta" },
  { id: 11, value: "Ebonyi", label: "Ebonyi" },
  { id: 12, value: "Edo", label: "Edo" },
  { id: 13, value: "Ekiti", label: "Ekiti" },
  { id: 14, value: "Enugu", label: "Enugu" },
  { id: 15, value: "Gombe", label: "Gombe" },
  { id: 16, value: "Imo", label: "Imo" },
  { id: 17, value: "Jigawa", label: "Jigawa" },
  { id: 18, value: "Kaduna", label: "Kaduna" },
  { id: 19, value: "Kano", label: "Kano" },
  { id: 20, value: "Katsina", label: "Katsina" },
  { id: 21, value: "Kebbi", label: "Kebbi" },
  { id: 22, value: "Kogi", label: "Kogi" },
  { id: 23, value: "Kwara", label: "Kwara" },
  { id: 24, value: "Lagos", label: "Lagos" },
  { id: 25, value: "Nasarawa", label: "Nasarawa" },
  { id: 26, value: "Niger", label: "Niger" },
  { id: 27, value: "Ogun", label: "Ogun" },
  { id: 28, value: "Ondo", label: "Ondo" },
  { id: 29, value: "Osun", label: "Osun" },
  { id: 30, value: "Oyo", label: "Oyo" },
  { id: 31, value: "Plateau", label: "Plateau" },
  { id: 32, value: "Rivers", label: "Rivers" },
  { id: 33, value: "Sokoto", label: "Sokoto" },
  { id: 34, value: "Taraba", label: "Taraba" },
  { id: 35, value: "Yobe", label: "Yobe" },
  { id: 36, value: "Zamfara", label: "Zamfara" },
  { id: 37, value: "FCT Abuja", label: "FCT Abuja" },
];

export const tableData = [
  {
    id: 1,
    firstName: "John",
    lastName: "Doe",
    phoneNumber: "08001234567",
    partner: "XYZ Corp",
    location: "Lagos",
    status: "Active",
  },
  {
    id: 2,
    firstName: "Jane",
    lastName: "Smith",
    phoneNumber: "08012345678",
    partner: "ABC Corp",
    location: "Abuja",
    status: "Awaiting approval",
  },
  {
    id: 3,
    firstName: "Alice",
    lastName: "Johnson",
    phoneNumber: "08023456789",
    partner: "DEF Corp",
    location: "Port Harcourt",
    status: "deactivated",
  },
  {
    id: 4,
    firstName: "Bob",
    lastName: "Williams",
    phoneNumber: "08034567890",
    partner: "GHI Corp",
    location: "Kano",
    status: "Active",
  },
  {
    id: 5,
    firstName: "Charlie",
    lastName: "Brown",
    phoneNumber: "08045678901",
    partner: "JKL Corp",
    location: "Ibadan",
    status: "Awaiting approval",
  },
  {
    id: 6,
    firstName: "Eva",
    lastName: "Davis",
    phoneNumber: "08056789012",
    partner: "MNO Corp",
    location: "Enugu",
    status: "Active",
  },
  {
    id: 7,
    firstName: "David",
    lastName: "Miller",
    phoneNumber: "08067890123",
    partner: "PQR Corp",
    location: "Abeokuta",
    status: "deactivated",
  },
  {
    id: 8,
    firstName: "Grace",
    lastName: "Taylor",
    phoneNumber: "08078901234",
    partner: "STU Corp",
    location: "Benin",
    status: "Awaiting approval",
  },
  {
    id: 9,
    firstName: "Frank",
    lastName: "Clark",
    phoneNumber: "08089012345",
    partner: "VWX Corp",
    location: "Jos",
    status: "Active",
  },
  {
    id: 10,
    firstName: "Helen",
    lastName: "Martin",
    phoneNumber: "08090123456",
    partner: "YZA Corp",
    location: "Kaduna",
    status: "deactivated",
  },
  {
    id: 11,
    firstName: "Ivan",
    lastName: "Wright",
    phoneNumber: "08101234567",
    partner: "BCD Corp",
    location: "Uyo",
    status: "Active",
  },
  {
    id: 12,
    firstName: "Jennifer",
    lastName: "Jones",
    phoneNumber: "08112345678",
    partner: "EFG Corp",
    location: "Makurdi",
    status: "Awaiting approval",
  },
  {
    id: 13,
    firstName: "Keith",
    lastName: "Johnson",
    phoneNumber: "08123456789",
    partner: "HIJ Corp",
    location: "Calabar",
    status: "deactivated",
  },
  {
    id: 14,
    firstName: "Linda",
    lastName: "Wilson",
    phoneNumber: "08134567890",
    partner: "KLM Corp",
    location: "Akure",
    status: "Active",
  },
  {
    id: 15,
    firstName: "Mark",
    lastName: "Young",
    phoneNumber: "08145678901",
    partner: "NOP Corp",
    location: "Warri",
    status: "Awaiting approval",
  },
  {
    id: 16,
    firstName: "Nancy",
    lastName: "Brown",
    phoneNumber: "08156789012",
    partner: "QRS Corp",
    location: "Asaba",
    status: "deactivated",
  },
  {
    id: 17,
    firstName: "Oscar",
    lastName: "Allen",
    phoneNumber: "08167890123",
    partner: "TUV Corp",
    location: "Aba",
    status: "Active",
  },
  {
    id: 18,
    firstName: "Pamela",
    lastName: "Lee",
    phoneNumber: "08178901234",
    partner: "WXY Corp",
    location: "Owerri",
    status: "Awaiting approval",
  },
  {
    id: 19,
    firstName: "Quincy",
    lastName: "Smith",
    phoneNumber: "08189012345",
    partner: "ZAB Corp",
    location: "Onitsha",
    status: "deactivated",
  },
  {
    id: 20,
    firstName: "Ryan",
    lastName: "Cooper",
    phoneNumber: "08190123456",
    partner: "CDE Corp",
    location: "Ilorin",
    status: "Active",
  },
];